//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPRequestsLib.wcfB2BRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfB2BRef.IwcfB2B")]
    public interface IwcfB2B {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAddress", ReplyAction="http://tempuri.org/IwcfB2B/sendAddressResponse")]
        string sendAddress(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAddress", ReplyAction="http://tempuri.org/IwcfB2B/sendAddressResponse")]
        System.Threading.Tasks.Task<string> sendAddressAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPrice", ReplyAction="http://tempuri.org/IwcfB2B/sendPriceResponse")]
        string sendPrice(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPrice", ReplyAction="http://tempuri.org/IwcfB2B/sendPriceResponse")]
        System.Threading.Tasks.Task<string> sendPriceAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAvailability", ReplyAction="http://tempuri.org/IwcfB2B/sendAvailabilityResponse")]
        string sendAvailability(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAvailability", ReplyAction="http://tempuri.org/IwcfB2B/sendAvailabilityResponse")]
        System.Threading.Tasks.Task<string> sendAvailabilityAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderPlacement", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderPlacementResponse")]
        string sendOrderPlacement(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderPlacement", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderPlacementResponse")]
        System.Threading.Tasks.Task<string> sendOrderPlacementAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderPlacementNew", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderPlacementNewResponse")]
        string sendOrderPlacementNew(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderPlacementNew", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderPlacementNewResponse")]
        System.Threading.Tasks.Task<string> sendOrderPlacementNewAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderStatus", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderStatusResponse")]
        string sendOrderStatus(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderStatus", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderStatusResponse")]
        System.Threading.Tasks.Task<string> sendOrderStatusAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderStatusTest", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderStatusTestResponse")]
        string sendOrderStatusTest(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderStatusTest", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderStatusTestResponse")]
        System.Threading.Tasks.Task<string> sendOrderStatusTestAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendCustomerRange", ReplyAction="http://tempuri.org/IwcfB2B/sendCustomerRangeResponse")]
        string sendCustomerRange(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendCustomerRange", ReplyAction="http://tempuri.org/IwcfB2B/sendCustomerRangeResponse")]
        System.Threading.Tasks.Task<string> sendCustomerRangeAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendConsumerAddress", ReplyAction="http://tempuri.org/IwcfB2B/sendConsumerAddressResponse")]
        string sendConsumerAddress(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendConsumerAddress", ReplyAction="http://tempuri.org/IwcfB2B/sendConsumerAddressResponse")]
        System.Threading.Tasks.Task<string> sendConsumerAddressAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendCountryRange", ReplyAction="http://tempuri.org/IwcfB2B/sendCountryRangeResponse")]
        string sendCountryRange(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendCountryRange", ReplyAction="http://tempuri.org/IwcfB2B/sendCountryRangeResponse")]
        System.Threading.Tasks.Task<string> sendCountryRangeAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessage", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageResponse")]
        string PutMessage(string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessage", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageResponse")]
        System.Threading.Tasks.Task<string> PutMessageAsync(string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendSaveVMIParameters", ReplyAction="http://tempuri.org/IwcfB2B/sendSaveVMIParametersResponse")]
        string sendSaveVMIParameters(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendSaveVMIParameters", ReplyAction="http://tempuri.org/IwcfB2B/sendSaveVMIParametersResponse")]
        System.Threading.Tasks.Task<string> sendSaveVMIParametersAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendGetVMIParameters", ReplyAction="http://tempuri.org/IwcfB2B/sendGetVMIParametersResponse")]
        string sendGetVMIParameters(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendGetVMIParameters", ReplyAction="http://tempuri.org/IwcfB2B/sendGetVMIParametersResponse")]
        System.Threading.Tasks.Task<string> sendGetVMIParametersAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendSaveCMIR", ReplyAction="http://tempuri.org/IwcfB2B/sendSaveCMIRResponse")]
        string sendSaveCMIR(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendSaveCMIR", ReplyAction="http://tempuri.org/IwcfB2B/sendSaveCMIRResponse")]
        System.Threading.Tasks.Task<string> sendSaveCMIRAsync(string message, bool BooReply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendMedia_Asset", ReplyAction="http://tempuri.org/IwcfB2B/sendMedia_AssetResponse")]
        bool sendMedia_Asset(string SOP, string correlid, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendMedia_Asset", ReplyAction="http://tempuri.org/IwcfB2B/sendMedia_AssetResponse")]
        System.Threading.Tasks.Task<bool> sendMedia_AssetAsync(string SOP, string correlid, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPrice_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendPrice_HybrisResponse")]
        bool sendPrice_Hybris(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword, int requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPrice_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendPrice_HybrisResponse")]
        System.Threading.Tasks.Task<bool> sendPrice_HybrisAsync(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword, int requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPriceCheckReplyPL_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendPriceCheckReplyPL_HybrisResponse")]
        bool sendPriceCheckReplyPL_Hybris(string PriceMessage, string PriceCorrelId, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPriceCheckReplyPL_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendPriceCheckReplyPL_HybrisResponse")]
        System.Threading.Tasks.Task<bool> sendPriceCheckReplyPL_HybrisAsync(string PriceMessage, string PriceCorrelId, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendCustomerRange_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendCustomerRange_HybrisResponse")]
        bool sendCustomerRange_Hybris(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_customerRange, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendCustomerRange_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendCustomerRange_HybrisResponse")]
        System.Threading.Tasks.Task<bool> sendCustomerRange_HybrisAsync(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_customerRange, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAvailability_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendAvailability_HybrisResponse")]
        bool sendAvailability_Hybris(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword, int requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAvailability_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendAvailability_HybrisResponse")]
        System.Threading.Tasks.Task<bool> sendAvailability_HybrisAsync(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword, int requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAvailabilityCheckReplyPL_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendAvailabilityCheckReplyPL_HybrisResponse")]
        bool sendAvailabilityCheckReplyPL_Hybris(string AvailMessage, string AvailCorrelId, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendAvailabilityCheckReplyPL_Hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendAvailabilityCheckReplyPL_HybrisResponse")]
        System.Threading.Tasks.Task<bool> sendAvailabilityCheckReplyPL_HybrisAsync(string AvailMessage, string AvailCorrelId, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderPlacement_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderPlacement_hybrisResponse")]
        bool sendOrderPlacement_hybris(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_placeorder, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderPlacement_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderPlacement_hybrisResponse")]
        System.Threading.Tasks.Task<bool> sendOrderPlacement_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_placeorder, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessageForVmiandCmir", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageForVmiandCmirResponse")]
        string PutMessageForVmiandCmir(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessageForVmiandCmir", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageForVmiandCmirResponse")]
        System.Threading.Tasks.Task<string> PutMessageForVmiandCmirAsync(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessageAddress", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageAddressResponse")]
        string PutMessageAddress(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessageAddress", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageAddressResponse")]
        System.Threading.Tasks.Task<string> PutMessageAddressAsync(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderSearch_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderSearch_hybrisResponse")]
        bool sendOrderSearch_hybris(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderSearch_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderSearch_hybrisResponse")]
        System.Threading.Tasks.Task<bool> sendOrderSearch_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderList_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderList_hybrisResponse")]
        bool sendOrderList_hybris(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendOrderList_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendOrderList_hybrisResponse")]
        System.Threading.Tasks.Task<bool> sendOrderList_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendGETCalendar_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendGETCalendar_hybrisResponse")]
        bool sendGETCalendar_hybris(string strMessage, string strCorrelId, string SOP_NAME, string webservice_GetCalendar, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendGETCalendar_hybris", ReplyAction="http://tempuri.org/IwcfB2B/sendGETCalendar_hybrisResponse")]
        System.Threading.Tasks.Task<bool> sendGETCalendar_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, string webservice_GetCalendar, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/SendConsummerAddress", ReplyAction="http://tempuri.org/IwcfB2B/SendConsummerAddressResponse")]
        bool SendConsummerAddress(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_consummerAddress, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/SendConsummerAddress", ReplyAction="http://tempuri.org/IwcfB2B/SendConsummerAddressResponse")]
        System.Threading.Tasks.Task<bool> SendConsummerAddressAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_consummerAddress, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPrice_Hybris_TP2", ReplyAction="http://tempuri.org/IwcfB2B/sendPrice_Hybris_TP2Response")]
        bool sendPrice_Hybris_TP2(string strCorrId, string strMsg, string Webservice_price, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPrice_Hybris_TP2", ReplyAction="http://tempuri.org/IwcfB2B/sendPrice_Hybris_TP2Response")]
        System.Threading.Tasks.Task<bool> sendPrice_Hybris_TP2Async(string strCorrId, string strMsg, string Webservice_price, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPlaceOrder_Asyn", ReplyAction="http://tempuri.org/IwcfB2B/sendPlaceOrder_AsynResponse")]
        bool sendPlaceOrder_Asyn(string strCorrId, string strMsg, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPlaceOrder_Asyn", ReplyAction="http://tempuri.org/IwcfB2B/sendPlaceOrder_AsynResponse")]
        System.Threading.Tasks.Task<bool> sendPlaceOrder_AsynAsync(string strCorrId, string strMsg, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessageRange", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageRangeResponse")]
        string PutMessageRange(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/PutMessageRange", ReplyAction="http://tempuri.org/IwcfB2B/PutMessageRangeResponse")]
        System.Threading.Tasks.Task<string> PutMessageRangeAsync(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPlaceOrderTP2_Async", ReplyAction="http://tempuri.org/IwcfB2B/sendPlaceOrderTP2_AsyncResponse")]
        bool sendPlaceOrderTP2_Async(string strMsg, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfB2B/sendPlaceOrderTP2_Async", ReplyAction="http://tempuri.org/IwcfB2B/sendPlaceOrderTP2_AsyncResponse")]
        System.Threading.Tasks.Task<bool> sendPlaceOrderTP2_AsyncAsync(string strMsg, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwcfB2BChannel : SAPRequestsLib.wcfB2BRef.IwcfB2B, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwcfB2BClient : System.ServiceModel.ClientBase<SAPRequestsLib.wcfB2BRef.IwcfB2B>, SAPRequestsLib.wcfB2BRef.IwcfB2B {
        
        public IwcfB2BClient() {
        }
        
        public IwcfB2BClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwcfB2BClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfB2BClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfB2BClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendAddress(string message, bool BooReply) {
            return base.Channel.sendAddress(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendAddressAsync(string message, bool BooReply) {
            return base.Channel.sendAddressAsync(message, BooReply);
        }
        
        public string sendPrice(string message, bool BooReply) {
            return base.Channel.sendPrice(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendPriceAsync(string message, bool BooReply) {
            return base.Channel.sendPriceAsync(message, BooReply);
        }
        
        public string sendAvailability(string message, bool BooReply) {
            return base.Channel.sendAvailability(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendAvailabilityAsync(string message, bool BooReply) {
            return base.Channel.sendAvailabilityAsync(message, BooReply);
        }
        
        public string sendOrderPlacement(string message, bool BooReply) {
            return base.Channel.sendOrderPlacement(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendOrderPlacementAsync(string message, bool BooReply) {
            return base.Channel.sendOrderPlacementAsync(message, BooReply);
        }
        
        public string sendOrderPlacementNew(string message, bool BooReply) {
            return base.Channel.sendOrderPlacementNew(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendOrderPlacementNewAsync(string message, bool BooReply) {
            return base.Channel.sendOrderPlacementNewAsync(message, BooReply);
        }
        
        public string sendOrderStatus(string message, bool BooReply) {
            return base.Channel.sendOrderStatus(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendOrderStatusAsync(string message, bool BooReply) {
            return base.Channel.sendOrderStatusAsync(message, BooReply);
        }
        
        public string sendOrderStatusTest(string message, bool BooReply) {
            return base.Channel.sendOrderStatusTest(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendOrderStatusTestAsync(string message, bool BooReply) {
            return base.Channel.sendOrderStatusTestAsync(message, BooReply);
        }
        
        public string sendCustomerRange(string message, bool BooReply) {
            return base.Channel.sendCustomerRange(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendCustomerRangeAsync(string message, bool BooReply) {
            return base.Channel.sendCustomerRangeAsync(message, BooReply);
        }
        
        public string sendConsumerAddress(string message, bool BooReply) {
            return base.Channel.sendConsumerAddress(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendConsumerAddressAsync(string message, bool BooReply) {
            return base.Channel.sendConsumerAddressAsync(message, BooReply);
        }
        
        public string sendCountryRange(string message) {
            return base.Channel.sendCountryRange(message);
        }
        
        public System.Threading.Tasks.Task<string> sendCountryRangeAsync(string message) {
            return base.Channel.sendCountryRangeAsync(message);
        }
        
        public string PutMessage(string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn) {
            return base.Channel.PutMessage(strMsg, lngTypeMsg, strQName, intCharacterSet, booReplyReturn);
        }
        
        public System.Threading.Tasks.Task<string> PutMessageAsync(string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn) {
            return base.Channel.PutMessageAsync(strMsg, lngTypeMsg, strQName, intCharacterSet, booReplyReturn);
        }
        
        public string sendSaveVMIParameters(string message, bool BooReply) {
            return base.Channel.sendSaveVMIParameters(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendSaveVMIParametersAsync(string message, bool BooReply) {
            return base.Channel.sendSaveVMIParametersAsync(message, BooReply);
        }
        
        public string sendGetVMIParameters(string message, bool BooReply) {
            return base.Channel.sendGetVMIParameters(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendGetVMIParametersAsync(string message, bool BooReply) {
            return base.Channel.sendGetVMIParametersAsync(message, BooReply);
        }
        
        public string sendSaveCMIR(string message, bool BooReply) {
            return base.Channel.sendSaveCMIR(message, BooReply);
        }
        
        public System.Threading.Tasks.Task<string> sendSaveCMIRAsync(string message, bool BooReply) {
            return base.Channel.sendSaveCMIRAsync(message, BooReply);
        }
        
        public bool sendMedia_Asset(string SOP, string correlid, string xml) {
            return base.Channel.sendMedia_Asset(SOP, correlid, xml);
        }
        
        public System.Threading.Tasks.Task<bool> sendMedia_AssetAsync(string SOP, string correlid, string xml) {
            return base.Channel.sendMedia_AssetAsync(SOP, correlid, xml);
        }
        
        public bool sendPrice_Hybris(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword, int requester) {
            return base.Channel.sendPrice_Hybris(strMsg, strCorrId, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME, Webservice_price, WebServiceUsername, WebServicePassword, requester);
        }
        
        public System.Threading.Tasks.Task<bool> sendPrice_HybrisAsync(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword, int requester) {
            return base.Channel.sendPrice_HybrisAsync(strMsg, strCorrId, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME, Webservice_price, WebServiceUsername, WebServicePassword, requester);
        }
        
        public bool sendPriceCheckReplyPL_Hybris(string PriceMessage, string PriceCorrelId, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPriceCheckReplyPL_Hybris(PriceMessage, PriceCorrelId, SOP_NAME, Webservice_price, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendPriceCheckReplyPL_HybrisAsync(string PriceMessage, string PriceCorrelId, string SOP_NAME, string Webservice_price, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPriceCheckReplyPL_HybrisAsync(PriceMessage, PriceCorrelId, SOP_NAME, Webservice_price, WebServiceUsername, WebServicePassword);
        }
        
        public bool sendCustomerRange_Hybris(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_customerRange, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendCustomerRange_Hybris(strMsg, strCorrId, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME, Webservice_customerRange, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendCustomerRange_HybrisAsync(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_customerRange, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendCustomerRange_HybrisAsync(strMsg, strCorrId, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME, Webservice_customerRange, WebServiceUsername, WebServicePassword);
        }
        
        public bool sendAvailability_Hybris(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword, int requester) {
            return base.Channel.sendAvailability_Hybris(strMsg, strCorrId, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME, Webservice_avail, WebServiceUsername, WebServicePassword, requester);
        }
        
        public System.Threading.Tasks.Task<bool> sendAvailability_HybrisAsync(string strMsg, string strCorrId, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword, int requester) {
            return base.Channel.sendAvailability_HybrisAsync(strMsg, strCorrId, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME, Webservice_avail, WebServiceUsername, WebServicePassword, requester);
        }
        
        public bool sendAvailabilityCheckReplyPL_Hybris(string AvailMessage, string AvailCorrelId, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendAvailabilityCheckReplyPL_Hybris(AvailMessage, AvailCorrelId, SOP_NAME, Webservice_avail, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendAvailabilityCheckReplyPL_HybrisAsync(string AvailMessage, string AvailCorrelId, string SOP_NAME, string Webservice_avail, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendAvailabilityCheckReplyPL_HybrisAsync(AvailMessage, AvailCorrelId, SOP_NAME, Webservice_avail, WebServiceUsername, WebServicePassword);
        }
        
        public bool sendOrderPlacement_hybris(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_placeorder, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendOrderPlacement_hybris(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_placeorder, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendOrderPlacement_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_placeorder, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendOrderPlacement_hybrisAsync(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_placeorder, WebServiceUsername, WebServicePassword);
        }
        
        public string PutMessageForVmiandCmir(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME) {
            return base.Channel.PutMessageForVmiandCmir(typemessage, strMsg, lngTypeMsg, strQName, intCharacterSet, booReplyReturn, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME);
        }
        
        public System.Threading.Tasks.Task<string> PutMessageForVmiandCmirAsync(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, bool booReplyReturn, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME) {
            return base.Channel.PutMessageForVmiandCmirAsync(typemessage, strMsg, lngTypeMsg, strQName, intCharacterSet, booReplyReturn, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME);
        }
        
        public string PutMessageAddress(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME) {
            return base.Channel.PutMessageAddress(typemessage, strMsg, lngTypeMsg, strQName, intCharacterSet, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME);
        }
        
        public System.Threading.Tasks.Task<string> PutMessageAddressAsync(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME) {
            return base.Channel.PutMessageAddressAsync(typemessage, strMsg, lngTypeMsg, strQName, intCharacterSet, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME);
        }
        
        public bool sendOrderSearch_hybris(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendOrderSearch_hybris(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_orderlist, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendOrderSearch_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendOrderSearch_hybrisAsync(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_orderlist, WebServiceUsername, WebServicePassword);
        }
        
        public bool sendOrderList_hybris(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendOrderList_hybris(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_orderlist, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendOrderList_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_orderlist, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendOrderList_hybrisAsync(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_orderlist, WebServiceUsername, WebServicePassword);
        }
        
        public bool sendGETCalendar_hybris(string strMessage, string strCorrelId, string SOP_NAME, string webservice_GetCalendar, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendGETCalendar_hybris(strMessage, strCorrelId, SOP_NAME, webservice_GetCalendar, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendGETCalendar_hybrisAsync(string strMessage, string strCorrelId, string SOP_NAME, string webservice_GetCalendar, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendGETCalendar_hybrisAsync(strMessage, strCorrelId, SOP_NAME, webservice_GetCalendar, WebServiceUsername, WebServicePassword);
        }
        
        public bool SendConsummerAddress(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_consummerAddress, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.SendConsummerAddress(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_consummerAddress, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> SendConsummerAddressAsync(string strMessage, string strCorrelId, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_consummerAddress, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.SendConsummerAddressAsync(strMessage, strCorrelId, SOP_NAME, U_ID, SESSIONID, Webservice_consummerAddress, WebServiceUsername, WebServicePassword);
        }
        
        public bool sendPrice_Hybris_TP2(string strCorrId, string strMsg, string Webservice_price, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPrice_Hybris_TP2(strCorrId, strMsg, Webservice_price, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendPrice_Hybris_TP2Async(string strCorrId, string strMsg, string Webservice_price, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPrice_Hybris_TP2Async(strCorrId, strMsg, Webservice_price, WebServiceUsername, WebServicePassword);
        }
        
        public bool sendPlaceOrder_Asyn(string strCorrId, string strMsg, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPlaceOrder_Asyn(strCorrId, strMsg, SOP_NAME, U_ID, SESSIONID, Webservice_PlaceOrder_Async, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendPlaceOrder_AsynAsync(string strCorrId, string strMsg, string SOP_NAME, System.Guid U_ID, System.Guid SESSIONID, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPlaceOrder_AsynAsync(strCorrId, strMsg, SOP_NAME, U_ID, SESSIONID, Webservice_PlaceOrder_Async, WebServiceUsername, WebServicePassword);
        }
        
        public string PutMessageRange(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME) {
            return base.Channel.PutMessageRange(typemessage, strMsg, lngTypeMsg, strQName, intCharacterSet, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME);
        }
        
        public System.Threading.Tasks.Task<string> PutMessageRangeAsync(string typemessage, string strMsg, long lngTypeMsg, string strQName, int intCharacterSet, System.Guid U_ID, System.Guid SESSIONID, int APPLICATIONEXECUTED, string SOP_NAME) {
            return base.Channel.PutMessageRangeAsync(typemessage, strMsg, lngTypeMsg, strQName, intCharacterSet, U_ID, SESSIONID, APPLICATIONEXECUTED, SOP_NAME);
        }
        
        public bool sendPlaceOrderTP2_Async(string strMsg, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPlaceOrderTP2_Async(strMsg, Webservice_PlaceOrder_Async, WebServiceUsername, WebServicePassword);
        }
        
        public System.Threading.Tasks.Task<bool> sendPlaceOrderTP2_AsyncAsync(string strMsg, string Webservice_PlaceOrder_Async, string WebServiceUsername, string WebServicePassword) {
            return base.Channel.sendPlaceOrderTP2_AsyncAsync(strMsg, Webservice_PlaceOrder_Async, WebServiceUsername, WebServicePassword);
        }
    }
}
